name: CI

on:
  push:
    tags: [ "v*.*.*" ]
    branches: [ "**" ]

jobs:
  pipeline:
    name: CI Pipeline
    env:
        CGO_ENABLED: 0 
        APP: ${{ github.event.repository.name }}
        VERSION: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.24 
    - name: Clone repo
      uses: actions/checkout@v3
    - name: Test 
      run: go test -v ./...
    - name: Verify build
      if: github.ref_type == 'branch'
      run: go build -ldflags="-X 'main.commit=${{ github.sha }}' -X 'main.tag=${{ env.VERSION }}'"
    - name: Build and package (linux/amd64)
      if: github.ref_type == 'tag'
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags="-X 'main.commit=${{ github.sha }}' -X 'main.tag=${{ env.VERSION }}'" -o build/linux-amd64/${{ env.APP }}
        tar -czvf build/${{ env.APP }}-${{ env.VERSION }}-linux-amd64.tar.gz -C build/linux-amd64 ${{ env.APP }}
    - name: Build and package (darwin/amd64)
      if: github.ref_type == 'tag'    
      run: |
        GOOS=darwin GOARCH=amd64 go build -ldflags="-X 'main.commit=${{ github.sha }}' -X 'main.tag=${{ env.VERSION }}'" -o build/darwin-amd64/${{ env.APP }}
        tar -czvf build/${{ env.APP }}-${{ env.VERSION }}-darwin-amd64.tar.gz -C build/darwin-amd64 ${{ env.APP }}
    - name: Build and package (darwin/arm64)
      if: github.ref_type == 'tag'
      run: |
        GOOS=darwin GOARCH=arm64 go build -ldflags="-X 'main.commit=${{ github.sha }}' -X 'main.tag=${{ env.VERSION }}'" -o build/darwin-arm64/${{ env.APP }} 
        tar -czvf build/${{ env.APP }}-${{ env.VERSION }}-darwin-arm64.tar.gz -C build/darwin-arm64 ${{ env.APP }}
    - name: Create release
      id: create_release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2 
      with:
        files: | 
          build/${{ env.APP }}-${{ env.VERSION }}-linux-amd64.tar.gz
          build/${{ env.APP }}-${{ env.VERSION }}-darwin-amd64.tar.gz
          build/${{ env.APP }}-${{ env.VERSION }}-darwin-arm64.tar.gz
    - name: Report
      if: github.ref_type == 'tag'
      run: | 
        echo "release url: ${{ steps.create_release.outputs.url }}"