name: ci

on:
  push:
    branches: [ "**" ]

env:
  CGO_ENABLED: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.24 
    - name: Clone repo
      uses: actions/checkout@v3
    - name: Build
      run: go build
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.24 
    - name: Clone repo
      uses: actions/checkout@v3
    - name: Test 
      run: go test -v ./...